apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app # Ensure this matches your deployment name
  minReplicas: 2 # Minimum number of pods
  maxReplicas: 10 # Maximum number of pods (adjust based on your scalability needs and cost considerations)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # Scale when CPU usage exceeds 70%
